version: "3"
services:
  postgres:
    image: postgres:13
    container_name: todolist-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - ${DB_PORT:-5434}:5432
  postgres-test:
    image: postgres:13
    container_name: todolist-test-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD:-postgres}
    ports:
      - ${DB_TEST_PORT:-5435}:5432
